### ISSUE TITLE
Not working in Linux

### ISSUE THREAD

**Issue by srini1603** [Quasar-Community/Quasar-Developer-Tools#11]
Hi I'm currently using one of the Arch Linux distros Xero Linux I have been using this extension on my windows machine which is working great but it was not working when I tried to run this on my Linux machine where  but both machines are the same so kindly see through it
![ma](https://user-images.githubusercontent.com/73424883/164446361-888fdb9b-8a58-4c76-a53e-c189d50f8a95.png)
t

**Comment by Mati02K** [comment]
I see the error is due to the case of the file location mentioned in the manifest file. Will assign your the work of changing the case. Change the case of eventpage in the manifest file.

**Comment by srini1603** [comment]
bug is rectified and changed
